[package]
name = "moxide-cli"
version = "0.1.0"
authors = ["AsterNighT <asternight@outlook.com>"]
license = "MIT"
edition = "2021"

[dependencies]
moxide ={ path = "../moxide" }
color-eyre = "0.6.3"
is_elevated = "0.1.2"
rustyline = "14.0.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
